"""Add follower_count to clubs

Revision ID: 331be70e771f
Revises: 960131c79efd
Create Date: 2026-08-26 02:20:29.977334+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331be70e771f'
down_revision: Union[str, Sequence[str], None] = '960131c79efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('follower_count', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'follower_count')
    # ### end Alembic commands ###
