"""Add display_order to clubs

Revision ID: 38b262db71a0
Revises: c9a35b93d3b7
Create Date: 2026-08-25 10:22:18.638185+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b262db71a0'
down_revision: Union[str, Sequence[str], None] = 'c9a35b93d3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('display_order', sa.Integer(),server_default='0', nullable=False))
    op.create_index('idx_reminder_pending', 'reminders', ['is_sent', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reminder_pending', table_name='reminders')
    op.drop_column('clubs', 'display_order')
    # ### end Alembic commands ###
