"""Initial database schema

Revision ID: 54dc915ec2d8
Revises: 
Create Date: 2026-07-24 05:38:17.028185+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54dc915ec2d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('users',
  sa.Column('id', sa.String(length=36), nullable=False),
  sa.Column('email', sa.String(length=255), nullable=False),
  sa.Column('hashed_password', sa.String(length=255), nullable=False),
  sa.Column('full_name', sa.String(length=100), nullable=False),
  sa.Column('role', sa.Enum('STUDENT', 'CLUB_ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
  sa.Column('phone_number', sa.String(length=20), nullable=True),
  sa.Column('created_at', sa.DateTime(), nullable=False),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
  op.create_table('clubs',
  sa.Column('id', sa.String(length=36), nullable=False),
  sa.Column('name', sa.String(length=150), nullable=False),
  sa.Column('category', sa.String(length=50), nullable=False),
  sa.Column('description', sa.Text(), nullable=True),
  sa.Column('logo_url', sa.String(length=500), nullable=True),
  sa.Column('facebook_url', sa.String(length=500), nullable=False),
  sa.Column('admin_id', sa.String(length=36), nullable=False),
  sa.Column('created_at', sa.DateTime(), nullable=False),
  sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=True)
  op.create_table('campaign_posts',
  sa.Column('id', sa.String(length=36), nullable=False),
  sa.Column('club_id', sa.String(length=36), nullable=False),
  sa.Column('type', sa.Enum('RECRUITMENT', 'MERCHANDISE', 'MAJOR_EVENT', name='posttype'), nullable=False),
  sa.Column('title', sa.String(length=200), nullable=False),
  sa.Column('summary', sa.Text(), nullable=False),
  sa.Column('fb_post_url', sa.String(length=500), nullable=False),
  sa.Column('action_url', sa.String(length=500), nullable=True),
  sa.Column('deadline', sa.DateTime(), nullable=True),
  sa.Column('is_active', sa.Boolean(), nullable=False),
  sa.Column('click_count', sa.Integer(), nullable=False),
  sa.Column('created_at', sa.DateTime(), nullable=False),
  sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_table('club_followers',
  sa.Column('user_id', sa.String(length=36), nullable=False),
  sa.Column('club_id', sa.String(length=36), nullable=False),
  sa.Column('created_at', sa.DateTime(), nullable=False),
  sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('user_id', 'club_id')
  )
  op.create_table('reminders',
  sa.Column('id', sa.String(length=36), nullable=False),
  sa.Column('user_id', sa.String(length=36), nullable=False),
  sa.Column('campaign_post_id', sa.String(length=36), nullable=False),
  sa.Column('scheduled_at', sa.DateTime(), nullable=False),
  sa.Column('is_sent', sa.Boolean(), nullable=False),
  sa.Column('created_at', sa.DateTime(), nullable=False),
  sa.ForeignKeyConstraint(['campaign_post_id'], ['campaign_posts.id'], ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id')
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('reminders')
  op.drop_table('club_followers')
  op.drop_table('campaign_posts')
  op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
  op.drop_table('clubs')
  op.drop_index(op.f('ix_users_email'), table_name='users')
  op.drop_table('users')
  # ### end Alembic commands ###
