"""fixing created_at server_default func.now

Revision ID: 6a202d5f249c
Revises: a1b2c3d4e5f6
Create Date: 2026-09-03 12:45:02.676288+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a202d5f249c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_posts', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('clubs', 'contact_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('clubs', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('clubs', 'facebook_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_constraint(op.f('clubs_contact_email_key'), 'clubs', type_='unique')
    op.create_index(op.f('ix_clubs_contact_email'), 'clubs', ['contact_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clubs_contact_email'), table_name='clubs')
    op.create_unique_constraint(op.f('clubs_contact_email_key'), 'clubs', ['contact_email'], postgresql_nulls_not_distinct=False)
    op.alter_column('clubs', 'facebook_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('clubs', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('clubs', 'contact_email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('campaign_posts', 'image_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
