"""adding email_message to post

Revision ID: 71db21ca47bb
Revises: 6a202d5f249c
Create Date: 2026-09-04 16:59:21.794356+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71db21ca47bb'
down_revision: Union[str, Sequence[str], None] = '6a202d5f249c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_posts', sa.Column('email_message', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_posts', 'email_message')
    # ### end Alembic commands ###
