"""Update clubs table

Revision ID: c9a35b93d3b7
Revises: de6aa79cfeb4
Create Date: 2026-07-27 03:20:54.501881+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a35b93d3b7'
down_revision: Union[str, Sequence[str], None] = 'de6aa79cfeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('clubs', sa.Column('code', sa.String(length=20), nullable=False))
  op.add_column('clubs', sa.Column('banner_url', sa.String(length=500), nullable=True))
  op.add_column('clubs', sa.Column('is_active', sa.Boolean(), nullable=False))
  op.create_index(op.f('ix_clubs_code'), 'clubs', ['code'], unique=True)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_clubs_code'), table_name='clubs')
  op.drop_column('clubs', 'is_active')
  op.drop_column('clubs', 'banner_url')
  op.drop_column('clubs', 'code')
  # ### end Alembic commands ###
