"""Added student_id in Models

Revision ID: de6aa79cfeb4
Revises: 54dc915ec2d8
Create Date: 2026-07-26 04:49:26.009845+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6aa79cfeb4'
down_revision: Union[str, Sequence[str], None] = '54dc915ec2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('users', sa.Column('student_id', sa.String(length=50), nullable=True))
  op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
  op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_users_student_id'), table_name='users')
  op.drop_column('users', 'is_active')
  op.drop_column('users', 'student_id')
  # ### end Alembic commands ###
